name: ios_calculator
description: "A simple iOS-style calculator with history and unit conversion."
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  math_expressions: ^2.2.1
  sqflite: ^2.3.2
  path: ^1.8.3

flutter:
  uses-material-design: true
